### ISSUE TITLE
Missing 2.6 and 2.7-dev docs

### ISSUE THREAD

**Issue by shadyabhi** [ruoshan/haproxy-docset#1]
Hi @ruoshan,

Thanks for creating this docset. Can we move to official source now? https://www.mail-archive.com/haproxy@formilux.org/msg42790.html

Link to docs: http://www.haproxy.org/#down

I noticed this could be a problem when I noticed there were no 2.6 docs published.

**Comment by ruoshan** [comment]
@shadyabhi Thank you for info! I will take a look some time this week.

**Comment by ruoshan** [comment]
Just update the v2.6.6 doc here: https://github.com/ruoshan/haproxy-docset/commit/297f668406a4ad4230c23cf82bc6aaf25449af0e . The docset on Dash app will be updated once this is merged: https://github.com/Kapeli/Dash-User-Contributions/pull/3986

I don't want to add the dev build (2.7). I have updated the readme on how to generate the doc using the (forked) official tool. You can build it on your own.
